---
title: "Getting started"
output:
  workflowr::wflow_html:
    toc: false
    code_folding: "none"
---

This page describes how to download the data and code used in this analysis,
set up the project directory and rerun the analysis. I have use the
[`workflowr`][workflowr] package to organise the analysis and insert
reproducibilty information into the output documents. The [`packrat`][packrat]
package has also been used to manage R package versions and dependencies.

Getting the code
================

All the code and outputs of analysis are available from GitHub at 
https://github.com/Chuang1118/FB5P-seq. If you want to replicate the 
analysis you can either fork the repository and clone it or download the 
repository as a zipped directory.

Once you have a local copy of the repository you should see the following
directory structure:

* `analysis/` - Contains the R Markdown documents with the various stages of
  analysis. These are numbered according to the order they should be run.
* `data/` - This directory contains the data files used in the analysis with
  each dataset in it's own sub-directory (see [Getting the data](#data) for
  details). Processed intermediate data files will also be placed here.
* `output/` - Directory for output files produced by the analysis, each analysis
  step has it's own sub-directory.
* `docs/` - This directory contains the analysis website hosted at 
  https://chuang1118.github.io/test.github.io/FB5Pseq, including image files.
* `R/` - R scripts with custom functions used in some analysis stages.
* `scripts/` - Python scripts and examples of how command line tools were run.
* `packrat/` - Directory created by `packrat` that contains details of the R
  packages and versions used in the analysis.
* `README.md` - README describing the project.
* `.Rprofile` - Custom R profile for the project including set up for
  `packrat` and `workflowr`.
* `.gitignore` - Details of files and directories that are excluded from the
  repository.
* `proj_distal.Rproj` - RStudio project file.

Installing R packages
=====================

R Packages and dependencies for this project are managed using
[`packrat`][packrat]. This should allow you to install and use the same package
versions as we have used for the analysis. `packrat` should automatically take
care of this process for you the first time that you open R in the project
directory. If for some reason this does not happen you may need to run the
following commands:

```r
#install.packages("packrat")
#packrat::restore()
```

Note that a clean install of all the required packages can take a significant
amount of time when the project is first opened.

Getting the data {#data}
================
<ul>
<li>custom_210421_h_huDistalExp1</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 2</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/210421_VH00228_51_AAAHM7WM5/Analysis/1/Data/fastq</code>
  <ul>
    <li>Distal_Exp1_FB5Pseq_P1_S1_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P1_S1_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P2_S2_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P2_S2_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P3_S3_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P3_S3_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P4_S4_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P4_S4_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P5_S5_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P5_S5_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P6_S6_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P6_S6_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P7_S7_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P8_S8_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P7_S7_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P8_S8_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P9_S9_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P9_S9_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P10_S10_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P10_S10_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P11_S11_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P11_S11_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P12_S12_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P12_S12_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P13_S13_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp1_FB5Pseq_P13_S13_L001_R1_001.fastq.gz</li>
  </ul>
</details>
<li>custom_211029_h_huDistalExp2</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 2</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/211029_VH00228_70_AAAN33JM5/Analysis/1/Data/fastq</code>
  <ul>
    <li>Distal_Exp2_FB5Pseq_P1_S1_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P1_S1_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P2_S2_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P2_S2_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P3_S3_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P3_S3_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P4_S4_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P4_S4_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P5_S5_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P5_S5_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P6_S6_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P6_S6_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P7_S7_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P8_S8_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P7_S7_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P8_S8_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P9_S9_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P9_S9_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P10_S10_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P10_S10_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P11_S11_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp2_FB5Pseq_P11_S11_L001_R1_001.fastq.gz</li>
  </ul>
</details>
<li>custom_211118_h_huDistalExp3</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 2</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/211118_VH00228_74_AAAN2VGM5/Analysis/1/Data/fastq</code>
  <ul>
    <li>Distal_Exp3_FB5Pseq_P12_S1_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P12_S1_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P13_S2_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P13_S2_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P14_S3_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P14_S3_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P15_S4_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P15_S4_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P16_S5_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P16_S5_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P17_S6_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P17_S6_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P18_S7_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P18_S7_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P19_S8_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P19_S8_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P20_S9_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P20_S9_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P21_S10_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P21_S10_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P22_S11_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P22_S11_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P23_S12_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P23_S12_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P24_S13_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp3_FB5Pseq_P24_S13_L001_R2_001.fastq.gz</li>
  </ul>
</details>
<li>custom_220210_h_huDistalExp4</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 2</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/220210_VH00228_84_AAATHVMM5/Analysis/1/Data/fastq</code>
  <ul>
    <li>Distal_Exp4_FB5Pseq_P1_S1_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P1_S1_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P2_S2_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P2_S2_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P3_S3_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P3_S3_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P4_S4_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P4_S4_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P5_S5_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P5_S5_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P6_S6_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P6_S6_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P7_S7_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P8_S8_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P7_S7_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P8_S8_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P9_S9_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P9_S9_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P10_S10_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P10_S10_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P11_S11_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P11_S11_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P12_S12_L001_R1_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P12_S12_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P13_S13_L001_R2_001.fastq.gz</li>
    <li>Distal_Exp4_FB5Pseq_P13_S13_L001_R1_001.fastq.gz</li>
  </ul>
</details>
<li>flash_230619_h_tetramer</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 4</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/230725_VH00228_192_AAAY3JTHV/Analysis/1/Data/fastq</code>
  <ul>
    <li>p1_S1_R1_001.fastq.gz</li>
    <li>p1_S1_R2_001.fastq.gz</li>
    <li>p2_S2_R1_001.fastq.gz</li>
    <li>p2_S2_R2_001.fastq.gz</li>
    <li>p3_S3_R1_001.fastq.gz</li>
    <li>p3_S3_R2_001.fastq.gz</li>
    <li>p4_S4_R1_001.fastq.gz</li>
    <li>p4_S4_R2_001.fastq.gz</li>
    <li>p5_S5_R1_001.fastq.gz</li>
    <li>p5_S5_R2_001.fastq.gz</li>
    <li>p6_S6_R2_001.fastq.gz</li>
    <li>p6_S6_R1_001.fastq.gz</li>
    <li>p7_S7_R1_001.fastq.gz</li>
    <li>p7_S7_R2_001.fastq.gz</li>
  </ul>
</details>
<li>flash_230626_h_minibulk</li>
<details><summary> <span style="color:red"> *FASTQ files: * </span> link to Figure 5</summary>
  <code>/mnt/DOSI/PMLAB/BIOINFO/DATA/Genomics/230725_VH00228_192_AAAY3JTHV/Analysis/1/Data/fastq</code>
  <ul>
    <li>p8_S8_R1_001.fastq.gz</li>
    <li>p8_S8_R2_001.fastq.gz</li>
    <li>p9_S9_R1_001.fastq.gz</li>
    <li>p9_S9_R2_001.fastq.gz</li>
    <li>p10_S10_R1_001.fastq.gz</li>
    <li>p10_S10_R2_001.fastq.gz</li>
    <li>p11_S11_R1_001.fastq.gz</li>
    <li>p11_S11_R2_001.fastq.gz</li>
    <li>p12_S12_R1_001.fastq.gz</li>
    <li>p12_S12_R2_001.fastq.gz</li>
  </ul>
</details>
</ul>

In this project I have used the liver tissue samples included
in GEO accession number [GSE137275][geo]. The GEO entry contains processed
expression matrices from FB5P-seq pipeline.
Some pre-processing of the dataset was done on the command line to produce
datasets in a form suitable for statistical analysis in R. These steps are 
described on the methods page and examples of commands for these steps are 
provided in the `scripts` directory. If you don't want to perform these steps 
yourself you can download the processed data from this
[Filesender repository][filesender] or [Zenodo repository][zenodo]. This repository also contains intermediate
files from the statistical analysis.

Once the processed data has been has been produced or downloaded it needs to be
placed in the correct location. The analysis code assumes the following
directory structure inside the `data/` directory:

* `cellranger/ for figure 3` - Output from the Cell Ranger pipeline
    * `barcodes.tsv.gz` - Unfiltered list of droplet barcodes
    * `features.tsv.gz` - List of annotated features in the dataset
    * `filterered_barcodes.tsv.gz` Filtered list of droplet barcodes
    * `matrix.mtx.gz` - Unfiltered expression matrix
* `processed/` - Intermediate files produced during the statistical analysis.
  This will be produced as code in the R Markdown files is run so aren't
  required to run the analysis. Files are numbered according to the document
  that produces them.
    * `filtered_endogenes_UMI.csv` - `csv` the expression matrix containing 
      selected cells(rows) and all genes(columns) following FB5P-seq's quality 
      control, raw data used during clustering analysis
    * `filtered_metadata_allFeatures.csv` - `csv` metadata corresponding 
      produced by FB5P-seq's quality control
    * `02-sc_seurat.rds` - `seurat` object with cluster labels
    * `02-sc_seurat_metadata.RData` - `RData` metadata file with results 
      from clustering analysis
    * `patient.integrated.rds` - `seurat` object used for gene set score
      analysis
* `published/` - (options) Results from the previously published analysis of this dataset
    * `?????.csv` - Cell cluster assignments from published
      analysis
* `references/` - References mentioned during the analysis and on the website
    * `references.bib` - BibTex file of references

Running the analysis
====================

The analysis directory contains the following analysis files:

* `02-fig2.html` - Reading of datasets produced using FB5P-seq, 
  annotation of the dataset.
* `05-fig3.html` - Reading of datasets produced using 10x Genomics, 
  annotation of the dataset.  
* `03-fig4.html` - Reading of datasets produced using Flash (FB5P-seq v2), 
  selection of high-quality cells, then scoring of the dataset.
* `04-suppfig2.html` - highlight some marker genes in cell cluster.
* `06-suppfig4.html` - Literature-based-gene set score analysis (FB5P-seq).
* `07-suppfig14.html` - Literature-based-gene set score analysis (Flash).
* `90-methods.html` - Description of methods used during the analysis.

As indicated by the numbering they should be run in this order. If you want to
rerun the entire analysis this can be easily done using `workflowr`.

```r
# rmarkdown::render_site('analysis/')
#workflowr::wflow_build(republish = TRUE)
```

It is important to consider the computer and environment you are using before
doing this. Running this analysis from scratch requires a considerable amount
of time, disk space and memory. Some stages of the analysis also assume that
multiple (up to 10) cores are available for processing. If you have fewer cores
available you will need to change the following line in the relevant files and
provide the number of cores that are available for use.

```r
#bpparam <- MulticoreParam(workers = 10)
```

It is also possible to run individual stages of the analysis, either by
providing the names of the file you want to run to `workflowr::wflow_build()` or
by manually knitting the document (for example using the 'Knit' button in
RStudio).

Caching
-------

To avoid having to repeatably re-run long running sections of the analysis I
have turned on caching in the analysis documents. However, this comes at a
tradeoff with disk space, useability and (potentially but unlikely if careful)
reproducibility. In most cases this should not be a problem but it is something
to be aware of. In particular there is a incompatibilty with caching and
`workflowr` that can cause images to not appear in the resulting HTML files (see
this [GitHub issue][workflowr-issue] for more details). If you have already run
part of the analysis (and therefore have a cache) and want to rerun a document
the safest option is the use the RStudio 'Knit' button.

[geo]: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137275 "GEO"
[zenodo]: https://doi.org/10.5281/zenodo.3403043 "Zenodo"
[sra]: https://www.ncbi.nlm.nih.gov/sra?term=SRPXXXXXX "SRA"
[filesender]: https://filesender.renater.fr/?s=download&token=3179da86-87cc-41a0-9576-74c53d804f11 "Filesender"
[packrat]: https://rstudio.github.io/packrat/ "Packrat"
[workflowr]: https://jdblischak.github.io/workflowr/ "Workflowr"
[workflowr-issue]: https://github.com/jdblischak/workflowr/issues/113 "Workflowr caching issue"

```{r session-info, eval = FALSE, echo = FALSE}
devtools::session_info()
```
